on: [push, pull_request]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup
        run: |
          chmod +x ./setup.sh
          ./setup.sh
      - name: Lint
        run: |
          . .venv/bin/activate
          chmod +x ./lint.sh
          ./lint.sh
      - name: Test
        run: |
          . .venv/bin/activate
          pytest
      - name: Build
        run: |
          . .venv/bin/activate
          chmod +x ./build.sh
          ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: shaders
          path: build/*.wasm
          if-no-files-found: error
